name: Tests

on: [push, pull_request]

jobs:
  testing:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        php: ['8.1', '8.2', '8.3']

    name: "OS ${{ matrix.os }} | PHP ${{ matrix.php }}"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none  # XDebug can be enabled here 'coverage: xdebug'
          tools: composer

      - uses: "ramsey/composer-install@v3"

      - name: Run tests
        run: composer test
